name: 'cosign executable'
description: 'Wrapper around the cosign executable'
author: samhclark

branding:
  icon: lock
  color: blue

inputs:
  args:
    description: 'Single string args to the `cosign` command'
    required: true
    default: 'version'
  each:
    description: |
      Newline separated parameters where each line is substituted in args, replacing `{}`.
      That is, `args` MUST contain `{}` if `each` is set.
      Practically, this lets you do `xargs -I {} cosign $args`.

runs:
  using: docker
  image: docker://ghcr.io/samhclark/cosign-exec-action:v1.0.2
  env:
    INPUT_ARGS: ${{ inputs.args }}
    INPUT_EACH: ${{ inputs.each }}
