name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test Container Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build the Container
        run: podman build -t cosign-exec-action:test .

      - name: Test - Simple Mode
        run: |
          podman run --rm \
            --env INPUT_ARGS=version \
            cosign-exec-action:test

      - name: Test - Each Mode
        run: |
          podman run --rm \
            --env INPUT_ARGS="{}" \
            --env INPUT_EACH=version \
            cosign-exec-action:test

      - name: Test - Each Mode Multi-line
        run: |
          podman run --rm \
            --env INPUT_ARGS="{}" \
            --env "INPUT_EACH=$(printf 'version\nversion')" \
            cosign-exec-action:test
